debug: false
logging:
  level:
    root: info
    com:
      jmgo:
        admin:
          mapper: info
server:
  port: 8880
  servlet:
    context-path: /

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/face?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: test
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    other:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=TzMedia
      #jdbc-url: jdbc:mysql://127.0.0.1:3306/face?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: appuser
      password: app@123
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 1000
      min-idle: 10
      stat-view-servlet:
        allow: true
      test-on-borrow: true
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: test     # 密码（默认为空）
    timeout: 60000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
#开发环境
jmgo:
  upload:
    chunkSize: 10485760
  debug : true
  synchronizeUser: true
  pubfile: D:\\data0\\uploads777777777777\\

face:
  privatekey : 9999
  publickey : 6666
  serverip : 127.0.0.1
  serverport : 8880
  uploaddir : D:\\faceupload\\
